apiVersion: apps/v1
kind: Deployment
metadata:
  name: location-master-data-lookup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: location-master-data-lookup
  template:
    metadata:
      labels:
        app: location-master-data-lookup
    spec:
      containers:
        - name: location-master-data-lookup
          image: locationpocacr.azurecr.io/location-master-data-lookup:v1
          ports:
            - containerPort: 8085
---
apiVersion: v1
kind: Service
metadata:
  name: location-master-data-lookup-service
spec:
  selector:
    app: location-master-data-lookup
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8085
  type: LoadBalancer