apiVersion: apps/v1
kind: Deployment
metadata:
  name: location-master-data-lookup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: location-master-data-lookup
  template:
    metadata:
      labels:
        app: location-master-data-lookup
    spec:
      containers:
        - name: location-master-data-lookup
          image: locationpocacr.azurecr.io/location-master-data-lookup:v1
          ports:
            - containerPort: 8082
---
#kind: Service
#apiVersion: v1
#metadata:
  # Name of our service
  #name: cloud-poc-service-producer
#spec:
  # LoadBalancer type to allow external access to multiple ports
  #type: LoadBalancer
  #selector:
    # Will deliver external traffic to the pod holding each of our containers
    #app: consumer
  #ports:
    #- name: sentiment
      #protocol: TCP
     #- port: 8082
      #targetPort: containerport