server.port=8085
server.servlet.context-path=/location-master-data-lookup

kafka.json.location.topic=test.json.data.topic.v1
#kafka.json.location.topic=json_data_topic
kafka.sasl.mechanism=PLAIN
kafka.security.protocol=SASL_SSL
kafka.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username= "CB5ZZ66L5FD6EVTG" password="BshPNV+wUV0v3ncEUajNZKmeznmJQmAcFH6Hf3mltSwsXb9JTRn7sxlKfKz71SBJ";
kafka.location.consumer.groupid=test.location.consumerGroup9.v1
#kafka.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username= "IMXVZ4C6WI4IMF64" password="KZnkIUgy399D0HohPbxt410v2L1YB44IBq0U3mz8mnLvV//LJ9mc4RLYmPPBZK2D";
#BshPNV+wUV0v3ncEUajNZKmeznmJQmAcFH6Hf3mltSwsXb9JTRn7sxlKfKz71SBJ

#spring.r2dbc.url=r2dbc:postgresql://localhost:49153/postgres?currentSchema=loader_svc
#spring.r2dbc.username=postgres
#spring.r2dbc.password=postgrespw
spring.r2dbc.url=r2dbc:postgresql://location-poc-postgres.postgres.database.azure.com:5432/postgres?currentSchema=locationpoc&sslMode=require
spring.r2dbc.username=postgres
spring.r2dbc.password=sql@123SQL